= Shoppomatic GonGo Proposed Architecture
:version: 1.0.1-SNAPSHOT
:imagesdir: diagrams

Version: {version}

== Introduction

Shoppomatic — a big e-commerce company that runs online c2c shopping platform (usually it's second-hand and used goods).
They are planning to expand their business by creating new trading opportunities for the platform audience — online
auction portal "GonGo". This document is the architecture design for the proposed application.

== General considerations

=== Users

The users of the application are verified. This assumes that there is a verification process. The stage of the process
has to be reflected in the structure of the user data structure, and the architecture should accommodate the
verification process optionally including third party actors, who may deliver services verifying the identity of certain
users.

=== User Verifier

Some external entity that verifies that a certain person solely bearing the information used for their authentication
has certain and verified external parameters. In layman terms, they have their real name, address etc. as it was
registered and is stored in the auction system. There may be more than one cerifiers who may verify different set of
parameters, and their verification may provide different verification strength.

=== Money Exchange Provider

An external actor may provide exchange rate between different currencies. Currency exchange rates are continuously
changing and thus allowing bids in different exchange rates introduce uncertainty. The auctioned good price is fixed
in a certain currency, and a bid in a different currency must be exchanged to the auction currency. The exchange can
happen at different times.

- at the time of the bidding
- at the time the auction is closed
- at the time of the money transfer

The exchange rate is likely be different between these times. The difference between the different exchange rates may
mean different advantages to different actors in the process.

== Actors

image::actors.svg[]

== Use Cases

image::usecase bidding.svg[]

== General Architecture

image::architecture.svg[]

The architecture is composed of several services. The services communicate with each other preferably using REST
protocol and HTTPS, but the general architecture does not depend on the actual communication and the technical details
of the service coupling.

The components on the picture are:

1. Management UI is a client application utilizing HTML, CSS, JavaScript (TypeScript) technologies.

2. UI is a client application utilizing HTML, CSS, JavaScript (TypeScript) technologies.

3. Management Presentation Service presents the data in JSON format as REST service for the management #interface#. The
   service connects to the internal systems. For the PoC these connections are not depicted on the diagram.

4. Presentation Service (PS) presents the data JSON formatted as REST service to the UI. This component connects to the
   business components that provide the basic functionality. The PS is responsible for authentication but not for
   authorization. Authorization is the responsibility of the business services.

5. Location Mapping Service connects to external services that identify the location of the client based on network
   address. This information and the browser supported geo location API together is the most reliable source of
   information about the client location.

6. Client Location Service is external service that gives information about client location.

7. Client Auction Feedback Service manages the business functionality related to feedback from users about closed
   auctions and transactions.

8. Auction Registy and Scheduler Service manages the business functionality related to register auctions and schedules.

9. Auction Execution Service is a compound component composed of many subcomponents (see the next section) that manages
   the bidding process and handles the individual transactions.

10. Exchange Calculator is an internal service fetches currency exchange data from external data provider, caches the
    rates and provides the data to the auction execution service and also stores historical data for reference purposes.
    Fetching the data can be scheduled and also triggered when some of the rates become volatile. This service manages
    also the list of allowed and not-allowed list of currencies. The service manages the load to the External Currency
    Ratio Provider.

11. External Currency Ratio Provider is an external service that should be used as reference to fetch currency exchange
    rates from.

12. User Registry manages the set of the users. This component stores the parameters of the registered users, and it
    also manages the user verification process. The API of the registry in later detailed design should consider that
    the registry data is split up between different territories.

13. Verification #Interface# is a unified interface that can communicate with the different external Verification
    Providers.

14. Verification Providers are external service providers, who provide user verification service either online or
    offline. The IF components provide different interfaces to these providers. Some of them may be as simple as JSON
    format converters. Some may be self standing applications with user interface where operators enter verification data
    that may have been processed on paper.

15. Reputation Calculator is an existing business analytics module that calculates the reputation points of the users.

16. Audit Trail Service processes audit messages. Audit messages will be stored electronically signed and chained into a
    signed chain. The digest or an encrypted form of the individual chain elements may be propagated back to the client
    ensuring that the auction site cannot change later the audit logs without compromising consistency.

17. DataWarehouse stores all transactional data for analysis purposes and to calculate statistical information in a
    scheduled manner.

18. Authentication is done using JWT tokens and OAuth protocol. This makes it possible to use external authentication
    services hardened with other measures if needed.

19. Event Queue is an Apache Kafka based message queue that serves information about events to all components that need
    to be informed. The Audit trails and the chat bot are also fed from this source.

20. Chatbot service is a chat component according to the requirements. The actual communication with the browser (HTTP
    polling, Web socket etc.) is implemented in a module in the Presentation Service. The Chat Bot is the business
    server component that manages, for example user subscriptions.

== Auction Subsystem Architecture

image::auction architecture.svg[]

To provide high performance and scalability the Auction Execution Service is split into two major parts.

1. Service Dispatcher and
2. Auction Service

The Auction Service runs on many instances. New instances may be started based on the increasing load and already
running instances can be shut down when the load is smaller. To provide high performance individual auctions are
assigned to certain nodes (one or more, but certainly only to a few). The Service Dispatcher administers which auction
runs on which nodes. This information is queried by the Presentation Service (PS) when querying bidding transaction data
or executing a bidding transaction. When the PS retrieves this information it communicates with the selected server.

The Auction Service manages the data using HBase NoSQL over Apache Hadoop infrastructure. This provides data scalability
on the infrastructure level.

The scalability of this architecture can be developed gradually as the load of the system increases creating ever new
releases of the softare.

1. The first version Service Dispatcher may manage a single node installed Auction Service that runs on a file
   backed HBase database.

2. As the scalability increases the HBase storage can be changed to Apache Hadoop.

3. When the bottleneck becomes the individual host then multiple hosts can be installed with load balancing using the
   same HBase instance (TODO: check that this is technically possible)

4. The final solution is to develop the fully functional Service Dispatcher.

Our expert estimation is that this architecture can handle a few hundred per second transaction on the 1st level, a few
thousand per second on the second level and practically there is no limit on the last level.





